// Generated by: "3DEN" call BIS_fnc_exportGUIBaseClasses;

// Control types
#define CT_STATIC           0
#define CT_BUTTON           1
#define CT_EDIT             2
#define CT_SLIDER           3
#define CT_COMBO            4
#define CT_LISTBOX          5
#define CT_TOOLBOX          6
#define CT_CHECKBOXES       7
#define CT_PROGRESS         8
#define CT_HTML             9
#define CT_STATIC_SKEW      10
#define CT_ACTIVETEXT       11
#define CT_TREE             12
#define CT_STRUCTURED_TEXT  13
#define CT_CONTEXT_MENU     14
#define CT_CONTROLS_GROUP   15
#define CT_SHORTCUTBUTTON   16
#define CT_HITZONES         17
#define CT_XKEYDESC         40
#define CT_XBUTTON          41
#define CT_XLISTBOX         42
#define CT_XSLIDER          43
#define CT_XCOMBO           44
#define CT_ANIMATED_TEXTURE 45
#define CT_OBJECT           80
#define CT_OBJECT_ZOOM      81
#define CT_OBJECT_CONTAINER 82
#define CT_OBJECT_CONT_ANIM 83
#define CT_LINEBREAK        98
#define CT_USER             99
#define CT_MAP              100
#define CT_MAP_MAIN         101
#define CT_LISTNBOX         102
#define CT_ITEMSLOT         103
#define CT_CHECKBOX         77

// Static styles
#define ST_POS            0x0F
#define ST_HPOS           0x03
#define ST_VPOS           0x0C
#define ST_LEFT           0x00
#define ST_RIGHT          0x01
#define ST_CENTER         0x02
#define ST_DOWN           0x04
#define ST_UP             0x08
#define ST_VCENTER        0x0C

#define ST_TYPE           0xF0
#define ST_SINGLE         0x00
#define ST_MULTI          0x10
#define ST_TITLE_BAR      0x20
#define ST_PICTURE        0x30
#define ST_FRAME          0x40
#define ST_BACKGROUND     0x50
#define ST_GROUP_BOX      0x60
#define ST_GROUP_BOX2     0x70
#define ST_HUD_BACKGROUND 0x80
#define ST_TILE_PICTURE   0x90
#define ST_WITH_RECT      0xA0
#define ST_LINE           0xB0
#define ST_UPPERCASE      0xC0
#define ST_LOWERCASE      0xD0

#define ST_SHADOW         0x100
#define ST_NO_RECT        0x200
#define ST_KEEP_ASPECT_RATIO  0x800

// Slider styles
#define SL_DIR            0x400
#define SL_VERT           0
#define SL_HORZ           0x400

#define SL_TEXTURES       0x10

// progress bar
#define ST_VERTICAL       0x01
#define ST_HORIZONTAL     0

// Listbox styles
#define LB_TEXTURES       0x10
#define LB_MULTI          0x20

// Tree styles
#define TR_SHOWROOT       1
#define TR_AUTOCOLLAPSE   2

// Default grid
#define GUI_GRID_WAbs			((safezoneW / safezoneH) min 1.2)
#define GUI_GRID_HAbs			(GUI_GRID_WAbs / 1.2)
#define GUI_GRID_W			(GUI_GRID_WAbs / 40)
#define GUI_GRID_H			(GUI_GRID_HAbs / 25)
#define GUI_GRID_X			(safezoneX)
#define GUI_GRID_Y			(safezoneY + safezoneH - GUI_GRID_HAbs)

// Default text sizes
#define GUI_TEXT_SIZE_SMALL		(GUI_GRID_H * 0.8)
#define GUI_TEXT_SIZE_MEDIUM		(GUI_GRID_H * 1)
#define GUI_TEXT_SIZE_LARGE		(GUI_GRID_H * 1.2)

// Pixel grid
#define pixelScale	0.50
#define GRID_W (pixelW * pixelGrid * pixelScale)
#define GRID_H (pixelH * pixelGrid * pixelScale)


class ctrlCheckbox: ctrlDefault
{
	type = CT_CHECKBOX;
	checked = 0;
	color[] = { 1, 1, 1, 0.7 };
	colorFocused[] = { 1, 1, 1, 1 };
	colorHover[] = { 1, 1, 1, 1 };
	colorPressed[] = { 1, 1, 1, 1 };
	colorDisabled[] = { 1, 1, 1, 0.25 };
	colorBackground[] = { 0, 0, 0, 0 };
	colorBackgroundFocused[] = { 0, 0, 0, 0 };
	colorBackgroundHover[] = { 0, 0, 0, 0 };
	colorBackgroundPressed[] = { 0, 0, 0, 0 };
	colorBackgroundDisabled[] = { 0, 0, 0, 0 };
	textureChecked = "\a3\3DEN\Data\Controls\ctrlCheckbox\textureChecked_ca.paa";
	textureUnchecked = "\a3\3DEN\Data\Controls\ctrlCheckbox\textureUnchecked_ca.paa";
	textureFocusedChecked = "\a3\3DEN\Data\Controls\ctrlCheckbox\textureChecked_ca.paa";
	textureFocusedUnchecked = "\a3\3DEN\Data\Controls\ctrlCheckbox\textureUnchecked_ca.paa";
	textureHoverChecked = "\a3\3DEN\Data\Controls\ctrlCheckbox\textureChecked_ca.paa";
	textureHoverUnchecked = "\a3\3DEN\Data\Controls\ctrlCheckbox\textureUnchecked_ca.paa";
	texturePressedChecked = "\a3\3DEN\Data\Controls\ctrlCheckbox\textureChecked_ca.paa";
	texturePressedUnchecked = "\a3\3DEN\Data\Controls\ctrlCheckbox\textureUnchecked_ca.paa";
	textureDisabledChecked = "\a3\3DEN\Data\Controls\ctrlCheckbox\textureChecked_ca.paa";
	textureDisabledUnchecked = "\a3\3DEN\Data\Controls\ctrlCheckbox\textureUnchecked_ca.paa";
	soundClick[] =
	{
		"\A3\ui_f\data\sound\RscButton\soundClick",
		0.09,
		1
	};
	soundEnter[] =
	{
		"\A3\ui_f\data\sound\RscButton\soundEnter",
		0.09,
		1
	};
	soundPush[] =
	{
		"\A3\ui_f\data\sound\RscButton\soundPush",
		0.09,
		1
	};
	soundEscape[] =
	{
		"\A3\ui_f\data\sound\RscButton\soundEscape",
		0.09,
		1
	};
	onCanDestroy = "";
	onDestroy = "";
	onMouseEnter = "";
	onMouseExit = "";
	onSetFocus = "";
	onKillFocus = "";
	onKeyDown = "";
	onKeyUp = "";
	onMouseButtonDown = "";
	onMouseButtonUp = "";
	onMouseButtonClick = "";
	onMouseButtonDblClick = "";
	onMouseZChanged = "";
	onMouseMoving = "";
	onMouseHolding = "";
	onCheckedChanged = "";
};
class ctrlCheckboxBaseline: ctrlCheckbox
{
	textureChecked = "\a3\3DEN\Data\Controls\ctrlCheckbox\baseline_textureChecked_ca.paa";
	textureUnchecked = "\a3\3DEN\Data\Controls\ctrlCheckbox\baseline_textureUnchecked_ca.paa";
	textureFocusedChecked = "\a3\3DEN\Data\Controls\ctrlCheckbox\baseline_textureChecked_ca.paa";
	textureFocusedUnchecked = "\a3\3DEN\Data\Controls\ctrlCheckbox\baseline_textureUnchecked_ca.paa";
	textureHoverChecked = "\a3\3DEN\Data\Controls\ctrlCheckbox\baseline_textureChecked_ca.paa";
	textureHoverUnchecked = "\a3\3DEN\Data\Controls\ctrlCheckbox\baseline_textureUnchecked_ca.paa";
	texturePressedChecked = "\a3\3DEN\Data\Controls\ctrlCheckbox\baseline_textureChecked_ca.paa";
	texturePressedUnchecked = "\a3\3DEN\Data\Controls\ctrlCheckbox\baseline_textureUnchecked_ca.paa";
	textureDisabledChecked = "\a3\3DEN\Data\Controls\ctrlCheckbox\baseline_textureChecked_ca.paa";
	textureDisabledUnchecked = "\a3\3DEN\Data\Controls\ctrlCheckbox\baseline_textureUnchecked_ca.paa";
};
class ctrlActivePicture: ctrlActiveText
{
	style = ST_MULTI + ST_TITLE_BAR;
	color[] = { 1, 1, 1, 1 };
};
class ctrlStatic: ctrlDefaultText
{
	type = CT_STATIC;
	colorBackground[] = { 0, 0, 0, 0 };
	text = "";
	lineSpacing = 1;
	fixedWidth = 0;
	colorText[] = { 1, 1, 1, 1 };
	colorShadow[] = { 0, 0, 0, 1 };
	moving = 0;
	autoplay = 0;
	loops = 0;
	tileW = 1;
	tileH = 1;
	onCanDestroy = "";
	onDestroy = "";
	onMouseEnter = "";
	onMouseExit = "";
	onSetFocus = "";
	onKillFocus = "";
	onKeyDown = "";
	onKeyUp = "";
	onMouseButtonDown = "";
	onMouseButtonUp = "";
	onMouseButtonClick = "";
	onMouseButtonDblClick = "";
	onMouseZChanged = "";
	onMouseMoving = "";
	onMouseHolding = "";
	onVideoStopped = "";
};
class ctrlControlsGroupNoScrollbars: ctrlControlsGroup
{
	class VScrollbar: VScrollBar
	{
		width = 0;
	};
	class HScrollbar: HScrollBar
	{
		height = 0;
	};
};
class ctrlStructuredText: ctrlDefaultText
{
	type = CT_STRUCTURED_TEXT;
	colorBackground[] = { 0, 0, 0, 0 };
	size = "4.32 * (1 / (getResolution select 3)) * pixelGrid * 0.5";
	text = "";
	class Attributes
	{
		align = "left";
		color = "#ffffff";
		colorLink = "";
		size = 1;
		font = "RobotoCondensedLight";
	};
	onCanDestroy = "";
	onDestroy = "";
};
class ctrlDefault
{
	access = 0;
	idc = -1;
	style = ST_LEFT;
	default = 0;
	show = 1;
	fade = 0;
	blinkingPeriod = 0;
	deletable = 0;
	x = 0;
	y = 0;
	w = 0;
	h = 0;
	tooltip = "";
	tooltipMaxWidth = 0.5;
	tooltipColorShade[] = { 0, 0, 0, 1 };
	tooltipColorText[] = { 1, 1, 1, 1 };
	tooltipColorBox[] = { 0, 0, 0, 0 };
	class ScrollBar
	{
		width = 0;
		height = 0;
		scrollSpeed = 0.06;
		arrowEmpty = "\a3\3DEN\Data\Controls\ctrlDefault\arrowEmpty_ca.paa";
		arrowFull = "\a3\3DEN\Data\Controls\ctrlDefault\arrowFull_ca.paa";
		border = "\a3\3DEN\Data\Controls\ctrlDefault\border_ca.paa";
		thumb = "\a3\3DEN\Data\Controls\ctrlDefault\thumb_ca.paa";
		color[] = { 1, 1, 1, 1 };
	};
};
class ctrlDefaultText: ctrlDefault
{
	sizeEx = "4.32 * (1 / (getResolution select 3)) * pixelGrid * 0.5";
	font = "RobotoCondensedLight";
	shadow = 1;
};
class ctrlDefaultButton: ctrlDefaultText
{
	soundClick[] =
	{
		"\A3\ui_f\data\sound\RscButton\soundClick",
		0.09,
		1
	};
	soundEnter[] =
	{
		"\A3\ui_f\data\sound\RscButton\soundEnter",
		0.09,
		1
	};
	soundPush[] =
	{
		"\A3\ui_f\data\sound\RscButton\soundPush",
		0.09,
		1
	};
	soundEscape[] =
	{
		"\A3\ui_f\data\sound\RscButton\soundEscape",
		0.09,
		1
	};
};
class ctrlStaticPicture: ctrlStatic
{
	style = ST_MULTI + ST_TITLE_BAR;
};
class ctrlStaticPictureKeepAspect: ctrlStaticPicture
{
	style = ST_MULTI + ST_TITLE_BAR + ST_KEEP_ASPECT_RATIO;
};
class ctrlStaticPictureTile: ctrlStatic
{
	style = ST_MULTI + ST_HUD_BACKGROUND;
};
class ctrlStaticFrame: ctrlStatic
{
	style = ST_FRAME;
};
class ctrlStaticLine: ctrlStatic
{
	style = ST_MULTI + ST_TITLE_BAR + ST_HUD_BACKGROUND;
};
class ctrlStaticMulti: ctrlStatic
{
	style = ST_MULTI + ST_NO_RECT;
};
class ctrlStaticBackground: ctrlStatic
{
	colorBackground[] = { 0.2, 0.2, 0.2, 1 };
};
class ctrlStaticOverlay: ctrlStatic
{
	colorBackground[] = { 0, 0, 0, 0.5 };
};
class ctrlStaticTitle: ctrlStatic
{
	moving = 1;
	colorBackground[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		1
	};
	colorText[] = { 1, 1, 1, 1 };
};
class ctrlStaticFooter: ctrlStatic
{
	colorBackground[] = { 0, 0, 0, 0.3 };
};
class ctrlStaticBackgroundDisable: ctrlStatic
{
	x = -4;
	y = -2;
	w = 8;
	h = 4;
	colorBackground[] = { 1, 1, 1, 0.5 };
};
class ctrlStaticBackgroundDisableTiles: ctrlStaticPictureTile
{
	x = -4;
	y = -2;
	w = 8;
	h = 4;
	text = "\a3\3DEN\Data\Displays\Display3DENEditAttributes\backgroundDisable_ca.paa";
	tileW = "8 / (32 * pixelW) ";
	tileH = "4 / (32 * pixelH) ";
	colorText[] = { 1, 1, 1, 0.05 };
};
class ctrlButton: ctrlDefaultButton
{
	type = CT_BUTTON;
	style = ST_CENTER + ST_FRAME + ST_HUD_BACKGROUND;
	colorBackground[] = { 0, 0, 0, 1 };
	colorBackgroundDisabled[] = { 0, 0, 0, 0.5 };
	colorBackgroundActive[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		1
	};
	colorFocused[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		1
	};
	font = "PuristaLight";
	text = "";
	colorText[] = { 1, 1, 1, 1 };
	colorDisabled[] = { 1, 1, 1, 0.25 };
	borderSize = 0;
	colorBorder[] = { 0, 0, 0, 0 };
	colorShadow[] = { 0, 0, 0, 0 };
	offsetX = 0;
	offsetY = 0;
	offsetPressedX = "pixelW";
	offsetPressedY = "pixelH";
	period = 0;
	periodFocus = 2;
	periodOver = 0.5;
	class KeyHints
	{
		class A
		{
			key = "0x00050000 + 0";
			hint = "KEY_XBOX_A";
		};
	};
	onCanDestroy = "";
	onDestroy = "";
	onMouseEnter = "";
	onMouseExit = "";
	onSetFocus = "";
	onKillFocus = "";
	onKeyDown = "";
	onKeyUp = "";
	onMouseButtonDown = "";
	onMouseButtonUp = "";
	onMouseButtonClick = "";
	onMouseButtonDblClick = "";
	onMouseZChanged = "";
	onMouseMoving = "";
	onMouseHolding = "";
	onButtonClick = "";
	onButtonDown = "";
	onButtonUp = "";
};
class ctrlButtonPicture: ctrlButton
{
	style = ST_CENTER + ST_MULTI + ST_TITLE_BAR;
};
class ctrlButtonPictureKeepAspect: ctrlButton
{
	style = ST_CENTER + ST_MULTI + ST_TITLE_BAR + ST_KEEP_ASPECT_RATIO;
};
class ctrlButtonOK: ctrlButton
{
	default = 1;
	idc = 1;
	text = "OK";
};
class ctrlButtonCancel: ctrlButton
{
	idc = 2;
	text = "Cancel";
};
class ctrlButtonClose: ctrlButtonCancel
{
	text = "Close";
};
class ctrlButtonToolbar: ctrlButtonPictureKeepAspect
{
	colorBackground[] = { 0, 0, 0, 0 };
	colorBackgroundDisabled[] = { 0, 0, 0, 0 };
};
class ctrlButtonSearch: ctrlButton
{
	style = ST_CENTER + ST_MULTI + ST_TITLE_BAR + ST_KEEP_ASPECT_RATIO;
	text = "\a3\3DEN\Data\Displays\Display3DEN\search_start_ca.paa";
	textSearch = "\a3\3DEN\Data\Displays\Display3DEN\search_end_ca.paa";
	tooltip = "Search";
};
class ctrlButtonExpandAll: ctrlButtonToolbar
{
	style = ST_CENTER + ST_MULTI + ST_TITLE_BAR + ST_KEEP_ASPECT_RATIO;
	text = "\a3\3DEN\Data\Displays\Display3DEN\tree_expand_ca.paa";
	tooltip = "Expand All";
};
class ctrlButtonCollapseAll: ctrlButtonToolbar
{
	style = ST_CENTER + ST_MULTI + ST_TITLE_BAR + ST_KEEP_ASPECT_RATIO;
	text = "\a3\3DEN\Data\Displays\Display3DEN\tree_collapse_ca.paa";
	tooltip = "Collapse All";
};
class ctrlButtonFilter: ctrlButton
{
	colorBackground[] = { 0, 0, 0, 0 };
	colorBackgroundDisabled[] = { 0, 0, 0, 0 };
	colorBackgroundActive[] = { 1, 1, 1, 0.3 };
	colorFocused[] = { 0, 0, 0, 0 };
};
class ctrlEdit: ctrlDefaultText
{
	type = CT_EDIT;
	colorBackground[] = { 0, 0, 0, 0.5 };
	text = "";
	colorText[] = { 1, 1, 1, 1 };
	colorDisabled[] = { 1, 1, 1, 0.25 };
	colorSelection[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		1
	};
	canModify = 1;
	autocomplete = "";
	onCanDestroy = "";
	onDestroy = "";
	onSetFocus = "";
	onKillFocus = "";
	onKeyDown = "";
	onKeyUp = "";
	onMouseButtonDown = "";
	onMouseButtonUp = "";
	onMouseButtonClick = "";
	onMouseButtonDblClick = "";
	onMouseZChanged = "";
	onMouseMoving = "";
	onMouseHolding = "";
};
class ctrlEditMulti: ctrlEdit
{
	style = ST_MULTI;
};
class ctrlSliderV: ctrlDefault
{
	type = CT_SLIDER;
	style = SL_VERT;
	color[] = { 0, 0, 0, 1 };
	colorDisabled[] = { 1, 1, 1, 0.25 };
	colorActive[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		1
	};
	sliderRange[] = { 0, 1 };
	sliderPosition = 1;
	lineSize = 0.1;
	pageSize = 3;
	class Title
	{
		idc = -1;
		colorBase[] = { 1, 1, 1, 1 };
		colorActive[] =
		{
			" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
			" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
			" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
			1
		};
	};
	class Value
	{
		idc = -1;
		format = "%.f";
		type = CT_STATIC;
		colorBase[] = { 1, 1, 1, 1 };
		colorActive[] =
		{
			" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
			" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
			" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
			1
		};
	};
	onCanDestroy = "";
	onDestroy = "";
	onSetFocus = "";
	onKillFocus = "";
	onKeyDown = "";
	onKeyUp = "";
	onMouseButtonDown = "";
	onMouseButtonUp = "";
	onMouseButtonClick = "";
	onMouseButtonDblClick = "";
	onMouseZChanged = "";
	onMouseMoving = "";
	onMouseHolding = "";
	onSliderPosChanged = "";
};
class ctrlSliderH: ctrlSliderV
{
	style = SL_HORZ;
};
class ctrlCombo: ctrlDefaultText
{
	type = CT_COMBO;
	style = ST_MULTI + ST_NO_RECT;
	colorBackground[] = { 0.05, 0.05, 0.05, 1 };
	colorSelectBackground[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		1
	};
	colorText[] = { 1, 1, 1, 1 };
	colorDisabled[] = { 1, 1, 1, 0.25 };
	colorSelect[] = { 0, 0, 0, 1 };
	colorTextRight[] = { 1, 1, 1, 1 };
	colorSelectRight[] = { 1, 1, 1, 0.25 };
	colorSelect2Right[] = { 1, 1, 1, 1 };
	colorPicture[] = { 1, 1, 1, 1 };
	colorPictureSelected[] = { 1, 1, 1, 1 };
	colorPictureDisabled[] = { 1, 1, 1, 0.25 };
	colorPictureRight[] = { 1, 1, 1, 1 };
	colorPictureRightSelected[] = { 1, 1, 1, 1 };
	colorPictureRightDisabled[] = { 1, 1, 1, 0.25 };
	arrowEmpty = "\a3\3DEN\Data\Controls\ctrlCombo\arrowEmpty_ca.paa";
	arrowFull = "\a3\3DEN\Data\Controls\ctrlCombo\arrowFull_ca.paa";
	wholeHeight = 12 * 5 * GRID_H;
	maxHistoryDelay = 1;
	soundExpand[] =
	{
		"\A3\ui_f\data\sound\RscCombo\soundExpand",
		0.1,
		1
	};
	soundCollapse[] =
	{
		"\A3\ui_f\data\sound\RscCombo\soundCollapse",
		0.1,
		1
	};
	soundSelect[] =
	{
		"\A3\ui_f\data\sound\RscCombo\soundSelect",
		0.1,
		1
	};
	class ComboScrollBar
	{
		width = 0;
		height = 0;
		scrollSpeed = 0.01;
		arrowEmpty = "\a3\3DEN\Data\Controls\ctrlDefault\arrowEmpty_ca.paa";
		arrowFull = "\a3\3DEN\Data\Controls\ctrlDefault\arrowFull_ca.paa";
		border = "\a3\3DEN\Data\Controls\ctrlDefault\border_ca.paa";
		thumb = "\a3\3DEN\Data\Controls\ctrlDefault\thumb_ca.paa";
		color[] = { 1, 1, 1, 1 };
	};
	onCanDestroy = "";
	onDestroy = "";
	onSetFocus = "";
	onKillFocus = "";
	onKeyDown = "";
	onKeyUp = "";
	onMouseButtonDown = "";
	onMouseButtonUp = "";
	onMouseButtonClick = "";
	onMouseButtonDblClick = "";
	onMouseZChanged = "";
	onMouseMoving = "";
	onMouseHolding = "";
	onLBSelChanged = "";
};
class ctrlComboToolbar: ctrlCombo
{
	colorBackground[] = { 0.05, 0.05, 0.05, 1 };
	colorSelectBackground[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		1
	};
	arrowEmpty = "\a3\3DEN\Data\Controls\ctrlCombo\arrowEmptyToolbar_ca.paa";
	arrowFull = "\a3\3DEN\Data\Controls\ctrlCombo\arrowEmptyToolbar_ca.paa";
	wholeHeight = 12 * 5 * GRID_H;
};
class ctrlListbox: ctrlDefaultText
{
	type = CT_LISTBOX;
	style = LB_TEXTURES;
	colorBackground[] = { 0, 0, 0, 0.5 };
	colorSelectBackground[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		1
	};
	colorSelectBackground2[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		1
	};
	colorShadow[] = { 0, 0, 0, 0.5 };
	colorDisabled[] = { 1, 1, 1, 0.25 };
	colorText[] = { 1, 1, 1, 1 };
	colorSelect[] = { 1, 1, 1, 1 };
	colorSelect2[] = { 1, 1, 1, 1 };
	colorTextRight[] = { 1, 1, 1, 1 };
	colorSelectRight[] = { 1, 1, 1, 1 };
	colorSelect2Right[] = { 1, 1, 1, 1 };
	colorPicture[] = { 1, 1, 1, 1 };
	colorPictureSelected[] = { 1, 1, 1, 1 };
	colorPictureDisabled[] = { 1, 1, 1, 0.25 };
	colorPictureRight[] = { 1, 1, 1, 1 };
	colorPictureRightSelected[] = { 1, 1, 1, 1 };
	colorPictureRightDisabled[] = { 1, 1, 1, 0.25 };
	period = 1;
	rowHeight = "4.32 * (1 / (getResolution select 3)) * pixelGrid * 0.5";
	itemSpacing = 0;
	maxHistoryDelay = 1;
	canDrag = 0;
	soundSelect[] =
	{
		"\A3\ui_f\data\sound\RscListbox\soundSelect",
		0.09,
		1
	};
	class ListScrollBar: ScrollBar
	{
	};
	onCanDestroy = "";
	onDestroy = "";
	onSetFocus = "";
	onKillFocus = "";
	onKeyDown = "";
	onKeyUp = "";
	onMouseButtonDown = "";
	onMouseButtonUp = "";
	onMouseButtonClick = "";
	onMouseButtonDblClick = "";
	onMouseZChanged = "";
	onMouseMoving = "";
	onMouseHolding = "";
	onLBSelChanged = "";
	onLBDblClick = "";
	onLBDrag = "";
	onLBDragging = "";
	onLBDrop = "";
};
class ctrlToolbox: ctrlDefaultText
{
	type = CT_TOOLBOX;
	style = ST_CENTER;
	colorBackground[] = { 0, 0, 0, 0.5 };
	colorText[] = { 1, 1, 1, 1 };
	colorTextSelect[] = { 1, 1, 1, 1 };
	rows = 1;
	columns = 1;
	strings[] = { };
	values[] = { };
	color[] = { 1, 0, 1, 1 };
	colorSelect[] = { 0, 0, 0, 0 };
	colorTextDisable[] = { 0, 0, 0, 0 };
	colorDisable[] = { 0, 0, 0, 0 };
	colorSelectedBg[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		1
	};
	onCanDestroy = "";
	onDestroy = "";
	onMouseEnter = "";
	onMouseExit = "";
	onSetFocus = "";
	onKillFocus = "";
	onKeyDown = "";
	onKeyUp = "";
	onMouseButtonDown = "";
	onMouseButtonUp = "";
	onMouseButtonClick = "";
	onMouseButtonDblClick = "";
	onMouseZChanged = "";
	onMouseMoving = "";
	onMouseHolding = "";
	onToolBoxSelChanged = "";
};
class ctrlToolboxPicture: ctrlToolbox
{
	style = ST_CENTER + ST_MULTI + ST_TITLE_BAR;
};
class ctrlToolboxPictureKeepAspect: ctrlToolbox
{
	style = ST_CENTER + ST_MULTI + ST_TITLE_BAR + ST_KEEP_ASPECT_RATIO;
};
class ctrlCheckboxes: ctrlDefaultText
{
	type = CT_CHECKBOXES;
	colorBackground[] = { 0, 0, 0, 0.5 };
	colorText[] = { 1, 1, 1, 1 };
	colorTextSelect[] = { 1, 1, 1, 1 };
	rows = 1;
	columns = 1;
	strings[] = { };
	checked_strings[] = { };
	color[] = { 1, 0, 1, 1 };
	colorSelect[] = { 0, 0, 0, 0 };
	colorTextDisable[] = { 0, 0, 0, 0 };
	colorDisable[] = { 0, 0, 0, 0 };
	colorSelectedBg[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		1
	};
	onCanDestroy = "";
	onDestroy = "";
	onMouseEnter = "";
	onMouseExit = "";
	onSetFocus = "";
	onKillFocus = "";
	onKeyDown = "";
	onKeyUp = "";
	onMouseButtonDown = "";
	onMouseButtonUp = "";
	onMouseButtonClick = "";
	onMouseButtonDblClick = "";
	onMouseZChanged = "";
	onMouseMoving = "";
	onMouseHolding = "";
	onCheckBoxesSelChanged = "";
};
class ctrlCheckboxesCheckbox: ctrlCheckboxes
{
	style = ST_MULTI + ST_TITLE_BAR;
	strings[] =
	{
		"\a3\3DEN\Data\Controls\ctrlCheckbox\textureUnchecked_ca.paa"
	};
	checked_strings[] =
	{
		"\a3\3DEN\Data\Controls\ctrlCheckbox\textureChecked_ca.paa"
	};
	colorBackground[] = { 0, 0, 0, 0 };
	colorSelectedBg[] = { 0, 0, 0, 0 };
};
class ctrlProgress: ctrlDefault
{
	type = CT_PROGRESS;
	texture = "#(argb, 8, 8, 3) color (1, 1, 1, 1) ";
	colorBar[] = { 1, 1, 1, 1 };
	colorFrame[] = { 0, 0, 0, 1 };
	onCanDestroy = "";
	onDestroy = "";
};
class ctrlHTML: ctrlDefaultText
{
	type = CT_HTML;
	colorBackground[] = { 0, 0, 0, 0 };
	colorText[] = { 1, 1, 1, 1 };
	colorBold[] = { 1, 1, 1, 0.5 };
	colorLink[] = { 1, 1, 1, 1 };
	colorLinkActive[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		1
	};
	colorPicture[] = { 1, 1, 1, 1 };
	colorPictureBorder[] = { 0, 0, 0, 0 };
	colorPictureLink[] = { 1, 1, 1, 1 };
	colorPictureSelected[] = { 1, 1, 1, 1 };
	prevPage = "\a3\3DEN\Data\Controls\CtrlHTML\prevPage_ca.paa";
	nextPage = "\a3\3DEN\Data\Controls\CtrlHTML\nextPage_ca.paa";
	filename = "";
	cycleLinks = 0;
	cycleAllLinks = 0;
	class P
	{
		font = "RobotoCondensedLight";
		fontBold = "RobotoCondensedBold";
		sizeEx = "4.32 * (1 / (getResolution select 3)) * pixelGrid * 0.5";
	};
	class H1: P
	{
		sizeEx = "5.58 * (1 / (getResolution select 3)) * pixelGrid * 0.5";
	};
	class H2: P
	{
		sizeEx = "4.86 * (1 / (getResolution select 3)) * pixelGrid * 0.5";
	};
	class H3: P
	{
	};
	class H4: P
	{
	};
	class H5: P
	{
	};
	class H6: P
	{
		font = "RobotoCondensedLight";
		fontBold = "RobotoCondensedLight";
	};
	onCanDestroy = "";
	onDestroy = "";
	onMouseEnter = "";
	onMouseExit = "";
	onSetFocus = "";
	onKillFocus = "";
	onKeyDown = "";
	onKeyUp = "";
	onMouseButtonDown = "";
	onMouseButtonUp = "";
	onMouseButtonClick = "";
	onMouseButtonDblClick = "";
	onMouseZChanged = "";
	onMouseMoving = "";
	onMouseHolding = "";
	onHTMLLink = "";
};
class ctrlActiveText: ctrlDefaultButton
{
	type = CT_ACTIVETEXT;
	text = "";
	color[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		0.75
	};
	colorActive[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		1
	};
	colorDisabled[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		1
	};
	onCanDestroy = "";
	onDestroy = "";
	onMouseEnter = "";
	onMouseExit = "";
	onSetFocus = "";
	onKillFocus = "";
	onKeyDown = "";
	onKeyUp = "";
	onMouseButtonDown = "";
	onMouseButtonUp = "";
	onMouseButtonClick = "";
	onMouseButtonDblClick = "";
	onMouseZChanged = "";
	onMouseMoving = "";
	onMouseHolding = "";
	onButtonClick = "";
	onButtonDown = "";
	onButtonUp = "";
};
class ctrlActivePictureKeepAspect: ctrlActiveText
{
	style = ST_MULTI + ST_TITLE_BAR + ST_KEEP_ASPECT_RATIO;
};
class ctrlTree: ctrlDefaultText
{
	type = CT_TREE;
	colorBorder[] = { 0, 0, 0, 1 };
	colorLines[] = { 0, 0, 0, 0 };
	colorBackground[] = { 0, 0, 0, 0 };
	colorSelect[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		1
	};
	colorMarked[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		0.5
	};
	colorMarkedSelected[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		1
	};
	colorText[] = { 1, 1, 1, 1 };
	colorSelectText[] = { 1, 1, 1, 1 };
	colorMarkedText[] = { 1, 1, 1, 1 };
	colorSearch[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		1
	};
	colorPicture[] = { 1, 1, 1, 1 };
	colorPictureSelected[] = { 1, 1, 1, 1 };
	colorPictureDisabled[] = { 1, 1, 1, 0.25 };
	colorPictureRight[] = { 1, 1, 1, 1 };
	colorPictureRightSelected[] = { 1, 1, 1, 1 };
	colorPictureRightDisabled[] = { 1, 1, 1, 0.25 };
	multiselectEnabled = 0;
	expandOnDoubleclick = 1;
	hiddenTexture = "\a3\3DEN\Data\Controls\ctrlTree\hiddenTexture_ca.paa";
	expandedTexture = "\a3\3DEN\Data\Controls\ctrlTree\expandedTexture_ca.paa";
	maxHistoryDelay = 1;
	disableKeyboardSearch = 0;
	class ScrollBar: ScrollBar
	{
		scrollSpeed = 0.05;
	};
	colorDisabled[] = { 0, 0, 0, 0 };
	colorArrow[] = { 0, 0, 0, 0 };
	onCanDestroy = "";
	onDestroy = "";
	onMouseEnter = "";
	onMouseExit = "";
	onSetFocus = "";
	onKillFocus = "";
	onKeyDown = "";
	onKeyUp = "";
	onMouseButtonDown = "";
	onMouseButtonUp = "";
	onMouseButtonClick = "";
	onMouseButtonDblClick = "";
	onMouseZChanged = "";
	onMouseMoving = "";
	onMouseHolding = "";
	onTreeSelChanged = "";
	onTreeLButtonDown = "";
	onTreeDblClick = "";
	onTreeExpanded = "";
	onTreeCollapsed = "";
	onTreeMouseExit = "";
};
class ctrlControlsGroup: ctrlDefault
{
	type = CT_CONTROLS_GROUP;
	style = ST_MULTI;
	x = 0;
	y = 0;
	w = 1;
	h = 1;
	class VScrollBar: ScrollBar
	{
		width = 2 * GRID_W;
		height = 0;
		autoScrollEnabled = 0;
		autoScrollDelay = 1;
		autoScrollRewind = 1;
		autoScrollSpeed = 1;
	};
	class HScrollBar: ScrollBar
	{
		width = 0;
		height = 2 * GRID_H;
	};
	onCanDestroy = "";
	onDestroy = "";
	onMouseButtonDown = "";
	onMouseButtonUp = "";
	onMouseButtonClick = "";
	onMouseButtonDblClick = "";
	onMouseZChanged = "";
	onMouseMoving = "";
	onMouseHolding = "";
};
class ctrlControlsGroupNoHScrollbars: ctrlControlsGroup
{
	class HScrollbar: HScrollBar
	{
		height = 0;
	};
};
class ctrlControlsGroupNoVScrollbars: ctrlControlsGroup
{
	class VScrollbar: VScrollBar
	{
		width = 0;
	};
};
class ctrlShortcutButton: ctrlDefaultButton
{
	type = CT_SHORTCUTBUTTON;
	style = ST_FRAME + ST_HUD_BACKGROUND;
	colorBackground[] = { 0, 0, 0, 1 };
	colorBackground2[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		1
	};
	colorBackgroundFocused[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		1
	};
	colorBackgroundActive[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		1
	};
	text = "";
	size = "4.86 * (1 / (getResolution select 3)) * pixelGrid * 0.5";
	shadow = 0;
	color[] = { 1, 1, 1, 1 };
	color2[] = { 1, 1, 1, 1 };
	colorFocused[] = { 1, 1, 1, 1 };
	colorDisabled[] = { 1, 1, 1, 0.25 };
	animTextureNormal = "#(argb, 8, 8, 3) color (1, 1, 1, 1) ";
	animTextureOver = "#(argb, 8, 8, 3) color (1, 1, 1, 1) ";
	animTexturePressed = "#(argb, 8, 8, 3) color (1, 1, 1, 1) ";
	animTextureFocused = "#(argb, 8, 8, 3) color (1, 1, 1, 1) ";
	animTextureDisabled = "#(argb, 8, 8, 3) color (1, 1, 1, 1) ";
	animTextureDefault = "#(argb, 8, 8, 3) color (1, 1, 1, 1) ";
	period = 1;
	periodFocus = 1;
	periodOver = 0.5;
	shortcuts[] =
	{
		"0x00050000 + 0",
		28,
		57,
		156
	};
	textureNoShortcut = "#(argb, 8, 8, 3) color (1, 1, 1, 1) ";
	class Attributes
	{
		align = "center";
		color = "#ffffff";
		font = "PuristaLight";
		shadow = 0;
	};
	class HitZone
	{
		left = 0;
		top = 0;
		right = 0;
		bottom = 0;
	};
	class TextPos
	{
		left = 0;
		top = 0;
		right = 0;
		bottom = 0;
	};
	class ShortcutPos
	{
		left = 0;
		top = 0;
		w = 0;
		h = 0;
	};
	onCanDestroy = "";
	onDestroy = "";
	onMouseEnter = "";
	onMouseExit = "";
	onSetFocus = "";
	onKillFocus = "";
	onKeyDown = "";
	onKeyUp = "";
	onMouseButtonDown = "";
	onMouseButtonUp = "";
	onMouseButtonClick = "";
	onMouseButtonDblClick = "";
	onMouseZChanged = "";
	onMouseMoving = "";
	onMouseHolding = "";
	onButtonClick = "";
	onButtonDown = "";
	onButtonUp = "";
};
class ctrlShortcutButtonOK: ctrlShortcutButton
{
	default = 1;
	idc = 1;
	text = "OK";
};
class ctrlShortcutButtonCancel: ctrlShortcutButton
{
	idc = 2;
	text = "Cancel";
};
class ctrlShortcutButtonSteam: ctrlShortcutButton
{
	colorBackground[] = { 0.0313726, 0.721569, 0.917647, 1 };
	textureNoShortcut = "\a3\3DEN\Data\Controls\CtrlShortcutButton\steam_ca.paa";
	class TextPos
	{
		left = 1.5 * 5 * GRID_W;
		top = 0;
		right = 0;
		bottom = 0;
	};
	class ShortcutPos
	{
		left = 0;
		top = 0;
		w = 5 * GRID_W;
		h = 5 * GRID_H;
	};
};
class ctrlXListbox: ctrlDefaultText
{
	type = CT_XLISTBOX;
	style = ST_CENTER + LB_TEXTURES + SL_HORZ;
	color[] = { 1, 1, 1, 1 };
	colorActive[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		1
	};
	colorText[] = { 1, 1, 1, 1 };
	colorSelect[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		1
	};
	colorDisabled[] = { 1, 1, 1, 0.25 };
	colorPicture[] = { 1, 1, 1, 1 };
	cycle = 1;
	arrowEmpty = "\a3\3DEN\Data\Controls\CtrlXSlider\arrowEmpty_ca.paa";
	arrowFull = "\a3\3DEN\Data\Controls\CtrlXSlider\arrowFull_ca.paa";
	border = "\a3\3DEN\Data\Controls\CtrlXSlider\border_ca.paa";
	soundSelect[] =
	{
		"\A3\ui_f\data\sound\RscListbox\soundSelect",
		0.09,
		1
	};
	onCanDestroy = "";
	onDestroy = "";
	onSetFocus = "";
	onKillFocus = "";
	onKeyDown = "";
	onKeyUp = "";
	onMouseButtonDown = "";
	onMouseButtonUp = "";
	onMouseButtonClick = "";
	onMouseButtonDblClick = "";
	onMouseZChanged = "";
	onMouseMoving = "";
	onMouseHolding = "";
	onLBSelChanged = "";
	onLBDblClick = "";
};
class ctrlXSliderV: ctrlDefault
{
	type = CT_XSLIDER;
	style = SL_VERT;
	color[] = { 1, 1, 1, 0.6 };
	colorActive[] = { 1, 1, 1, 1 };
	colorDisabled[] = { 1, 1, 1, 0.25 };
	sliderRange[] = { 0, 1 };
	sliderPosition = 1;
	lineSize = 0.1;
	arrowEmpty = "\a3\3DEN\Data\Controls\CtrlXSlider\arrowEmpty_ca.paa";
	arrowFull = "\a3\3DEN\Data\Controls\CtrlXSlider\arrowFull_ca.paa";
	border = "\a3\3DEN\Data\Controls\CtrlXSlider\border_ca.paa";
	thumb = "\a3\3DEN\Data\Controls\CtrlXSlider\thumb_ca.paa";
	class Title
	{
		idc = -1;
		colorBase[] = { 1, 1, 1, 1 };
		colorActive[] =
		{
			" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
			" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
			" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
			1
		};
	};
	class Value
	{
		idc = -1;
		format = "%.f";
		type = CT_STATIC;
		colorBase[] = { 1, 1, 1, 1 };
		colorActive[] =
		{
			" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
			" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
			" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
			1
		};
	};
	onCanDestroy = "";
	onDestroy = "";
	onSetFocus = "";
	onKillFocus = "";
	onKeyDown = "";
	onKeyUp = "";
	onMouseButtonDown = "";
	onMouseButtonUp = "";
	onMouseButtonClick = "";
	onMouseButtonDblClick = "";
	onMouseZChanged = "";
	onMouseMoving = "";
	onMouseHolding = "";
	onSliderPosChanged = "";
};
class ctrlXSliderH: ctrlXSliderV
{
	style = SL_HORZ;
};
class ctrlMenu: ctrlDefaultText
{
	type = 46;
	font = "RobotoCondensedLight";
	colorBorder[] = { 0, 0, 0, 0 };
	colorBackground[] = { 0, 0, 0, 1 };
	colorText[] = { 1, 1, 1, 1 };
	colorSelect[] = { 0, 0, 0, 1 };
	colorSelectBackground[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		1
	};
	colorDisabled[] = { 1, 1, 1, 0.25 };
	colorPicture[] = { 1, 1, 1, 1 };
	colorPictureSelect[] = { 0, 0, 0, 1 };
	colorPictureDisabled[] = { 1, 1, 1, 0.5 };
	arrow = "\a3\3DEN\Data\Controls\ctrlMenu\arrow_ca.paa";
	rowHeight = 0;
	itemSpacingW = 0.01;
	itemSpacingH = 0.01;
	pictureCheckboxEnabled = "\a3\3DEN\Data\Controls\CtrlMenu\pictureCheckboxEnabled_ca.paa";
	pictureCheckboxDisabled = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
	pictureRadioEnabled = "\a3\3DEN\Data\Controls\CtrlMenu\pictureRadioEnabled_ca.paa";
	pictureRadioDisabled = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
};
class ctrlMenuStrip: ctrlMenu
{
	type = 47;
	colorStripBackground[] = { 0, 0, 0, 1 };
	colorStripText[] = { 1, 1, 1, 1 };
	colorStripSelect[] = { 0, 0, 0, 1 };
	colorStripSelectBackground[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		1
	};
	colorStripDisabled[] = { 1, 1, 1, 0.25 };
};
class ctrlMap: ctrlDefault
{
	type = CT_MAP_MAIN;
	style = ST_MULTI + ST_TITLE_BAR;
	x = "safezoneXAbs";
	y = "safezoneY";
	w = "safezoneWAbs";
	h = "safezoneH";
	sizeEx = 0.05;
	font = "RobotoCondensedLight";
	colorText[] = { 0, 0, 0, 1 };
	moveOnEdges = 1;
	ptsPerSquareSea = 5;
	ptsPerSquareTxt = 20;
	ptsPerSquareCLn = 10;
	ptsPerSquareExp = 10;
	ptsPerSquareCost = 10;
	ptsPerSquareFor = 9;
	ptsPerSquareForEdge = 9;
	ptsPerSquareObj = 9;
	ptsPerSquareForLod1 = 4;
	ptsPerSquareForLod2 = 1;
	ptsPerSquareRoad = 6;
	ptsPerSquareMainRoad = 6;
	ptsPerSquareRoadSimple = 1;
	ptsPerSquareMainRoadSimple = 1;
	drawShaded = 0.25;
	shadedSea = 0.3;
	runwayFont = "LCD14";
	scaleMin = 0.0001;
	scaleMax = 1;
	scaleDefault = 0.16;
	maxSatelliteAlpha = 0.85;
	alphaFadeStartScale = 2;
	alphaFadeEndScale = 2;
	text = "#(argb, 8, 8, 3) color (1, 1, 1, 1) ";
	colorBackground[] = { 0.969, 0.957, 0.949, 1 };
	colorOutside[] = { 0, 0, 0, 1 };
	colorSea[] = { 0.467, 0.631, 0.851, 0.5 };
	colorForest[] = { 0.624, 0.78, 0.388, 0.5 };
	colorForestTextured[] = { 0.624, 0.78, 0.388, 0.25 };
	colorForestBorder[] = { 0, 0, 0, 0 };
	colorRocks[] = { 0, 0, 0, 0.3 };
	colorRocksBorder[] = { 0, 0, 0, 0 };
	colorLevels[] = { 0.286, 0.177, 0.094, 0.5 };
	colorMainCountlines[] = { 0.572, 0.354, 0.188, 0.5 };
	colorCountlines[] = { 0.572, 0.354, 0.188, 0.25 };
	colorMainCountlinesWater[] = { 0.491, 0.577, 0.702, 0.6 };
	colorCountlinesWater[] = { 0.491, 0.577, 0.702, 0.3 };
	colorPowerLines[] = { 0.1, 0.1, 0.1, 1 };
	colorRailWay[] = { 1, 0, 0, 1 };
	colorNames[] = { 0.1, 0.1, 0.1, 0.9 };
	colorInactive[] = { 1, 1, 1, 0.5 };
	colorTracks[] = { 0.84, 0.76, 0.65, 0.15 };
	colorTracksFill[] = { 0.84, 0.76, 0.65, 1 };
	colorRoads[] = { 0.7, 0.7, 0.7, 1 };
	colorRoadsFill[] = { 1, 1, 1, 1 };
	colorMainRoads[] = { 0.9, 0.5, 0.3, 1 };
	colorMainRoadsFill[] = { 1, 0.6, 0.4, 1 };
	colorTrails[] = { 0.84, 0.76, 0.65, 0.15 };
	colorTrailsFill[] = { 0.84, 0.76, 0.65, 0.65 };
	colorGrid[] = { 0.1, 0.1, 0.1, 0.6 };
	colorGridMap[] = { 0.1, 0.1, 0.1, 0.6 };
	widthRailWay = 4;
	fontLabel = "RobotoCondensedLight";
	sizeExLabel = 0.05;
	fontGrid = "TahomaB";
	sizeExGrid = 0.02;
	fontUnits = "TahomaB";
	sizeExUnits = 0.05;
	fontNames = "RobotoCondensed";
	sizeExNames = 0.05;
	fontInfo = "RobotoCondensedLight";
	sizeExInfo = 0.05;
	fontLevel = "TahomaB";
	sizeExLevel = 0.02;
	showCountourInterval = 1;
	idcMarkerColor = -1;
	idcMarkerIcon = -1;
	textureComboBoxColor = "#(argb, 8, 8, 3) color (1, 1, 1, 1) ";
	showMarkers = "true";
	class LineMarker
	{
		lineWidthThin = 0.008;
		lineWidthThick = 0.014;
		lineDistanceMin = 3e - 005;
		lineLengthMin = 5;
	};
	class Legend
	{
		x = 0.5;
		y = 0.5;
		w = 0.4;
		h = 0.1;
		color[] = { 0, 0, 0, 1 };
		colorBackground[] = { 1, 1, 1, 0.5 };
		font = "RobotoCondensedLight";
		sizeEX = "3.96 * (1 / (getResolution select 3)) * pixelGrid * 0.5";
	};
	class Task
	{
		icon = "\A3\ui_f\data\map\mapcontrol\taskIcon_CA.paa";
		color[] = { 1, 1, 1, 1 };
		iconCreated = "\A3\ui_f\data\map\mapcontrol\taskIconCreated_CA.paa";
		colorCreated[] = { 1, 1, 0, 1 };
		iconCanceled = "\A3\ui_f\data\map\mapcontrol\taskIconCanceled_CA.paa";
		colorCanceled[] = { 0.7, 0.7, 0.7, 1 };
		iconDone = "\A3\ui_f\data\map\mapcontrol\taskIconDone_CA.paa";
		colorDone[] = { 0.7, 1, 0.3, 1 };
		iconFailed = "\A3\ui_f\data\map\mapcontrol\taskIconFailed_CA.paa";
		colorFailed[] = { 1, 0.3, 0.2, 1 };
		size = 27;
		importance = 1;
		coefMin = 1;
		coefMax = 1;
	};
	class ActiveMarker
	{
		color[] = { 0, 0, 0, 1 };
		size = 2;
	};
	class Waypoint
	{
		coefMax = 1;
		coefMin = 1;
		color[] = { 0, 0, 0, 1 };
		icon = "\A3\ui_f\data\map\mapcontrol\waypoint_ca.paa";
		importance = 1;
		size = 24;
	};
	class WaypointCompleted: Waypoint
	{
		icon = "\A3\ui_f\data\map\mapcontrol\waypointCompleted_ca.paa";
	};
	class CustomMark: Waypoint
	{
		icon = "\A3\ui_f\data\map\mapcontrol\custommark_ca.paa";
	};
	class Command: Waypoint
	{
		color[] = { 1, 1, 1, 1 };
		icon = "\A3\ui_f\data\map\mapcontrol\waypoint_ca.paa";
		size = 18;
	};
	class Bush: Waypoint
	{
		coefMax = 4;
		coefMin = 0.25;
		color[] = { 0.45, 0.64, 0.33, 0.4 };
		icon = "\A3\ui_f\data\map\mapcontrol\bush_ca.paa";
		importance = 0.007;
		size = 7;
	};
	class SmallTree: Bush
	{
		icon = "\A3\ui_f\data\map\mapcontrol\bush_ca.paa";
		importance = 0.36;
		size = 12;
	};
	class Tree: SmallTree
	{
		icon = "\A3\ui_f\data\map\mapcontrol\bush_ca.paa";
		importance = 0.72;
	};
	class Rock: SmallTree
	{
		color[] = { 0.1, 0.1, 0.1, 0.8 };
		icon = "\A3\ui_f\data\map\mapcontrol\rock_ca.paa";
		importance = 0.3;
	};
	class BusStop: Bush
	{
		color[] = { 0.45, 0.64, 0.33, 0.4 };
		icon = "\A3\ui_f\data\map\mapcontrol\bush_ca.paa";
	};
	class FuelStation: Waypoint
	{
		coefMax = 1;
		coefMin = 0.85;
		color[] = { 1, 1, 1, 1 };
		icon = "\A3\ui_f\data\map\mapcontrol\fuelstation_CA.paa";
	};
	class Hospital: FuelStation
	{
		icon = "\A3\ui_f\data\map\mapcontrol\hospital_CA.paa";
	};
	class Church: FuelStation
	{
		icon = "\A3\ui_f\data\map\mapcontrol\church_CA.paa";
	};
	class Lighthouse: FuelStation
	{
		icon = "\A3\ui_f\data\map\mapcontrol\lighthouse_CA.paa";
	};
	class Power: FuelStation
	{
		icon = "\A3\ui_f\data\map\mapcontrol\power_CA.paa";
	};
	class PowerSolar: FuelStation
	{
		icon = "\A3\ui_f\data\map\mapcontrol\powersolar_CA.paa";
	};
	class PowerWave: FuelStation
	{
		icon = "\A3\ui_f\data\map\mapcontrol\powerwave_CA.paa";
	};
	class PowerWind: FuelStation
	{
		icon = "\A3\ui_f\data\map\mapcontrol\powerwind_CA.paa";
	};
	class Quay: FuelStation
	{
		icon = "\A3\ui_f\data\map\mapcontrol\quay_CA.paa";
	};
	class Transmitter: FuelStation
	{
		icon = "\A3\ui_f\data\map\mapcontrol\transmitter_CA.paa";
	};
	class Watertower: FuelStation
	{
		icon = "\A3\ui_f\data\map\mapcontrol\watertower_CA.paa";
	};
	class Cross: Waypoint
	{
		color[] = { 0, 0, 0, 1 };
		icon = "\A3\ui_f\data\map\mapcontrol\Cross_CA.paa";
	};
	class Chapel: Cross
	{
		icon = "\A3\ui_f\data\map\mapcontrol\Chapel_CA.paa";
	};
	class Shipwreck: Cross
	{
		icon = "\A3\ui_f\data\map\mapcontrol\Shipwreck_CA.paa";
	};
	class Bunker: Waypoint
	{
		coefMax = 4;
		coefMin = 0.25;
		color[] = { 0, 0, 0, 1 };
		icon = "\A3\ui_f\data\map\mapcontrol\bunker_ca.paa";
		importance = 1.05;
		size = 14;
	};
	class Fortress: Bunker
	{
		icon = "\A3\ui_f\data\map\mapcontrol\bunker_ca.paa";
		importance = 1.6;
		size = 16;
	};
	class Fountain: Bunker
	{
		icon = "\A3\ui_f\data\map\mapcontrol\fountain_ca.paa";
		importance = 0.6;
		size = 11;
	};
	class Ruin: Waypoint
	{
		coefMax = 4;
		coefMin = 1;
		icon = "\A3\ui_f\data\map\mapcontrol\ruin_ca.paa";
		importance = 0.96;
		size = 16;
	};
	class Stack: Waypoint
	{
		coefMax = 2;
		coefMin = 0.4;
		icon = "\A3\ui_f\data\map\mapcontrol\stack_ca.paa";
		importance = 1.6;
		size = 16;
	};
	class Tourism: Waypoint
	{
		coefMax = 4;
		coefMin = 0.7;
		icon = "\A3\ui_f\data\map\mapcontrol\tourism_ca.paa";
		importance = 2.8;
		size = 16;
	};
	class ViewTower: Waypoint
	{
		coefMax = 4;
		coefMin = 0.5;
		icon = "\A3\ui_f\data\map\mapcontrol\viewtower_ca.paa";
		importance = 2;
		size = 16;
	};
	onCanDestroy = "";
	onDestroy = "";
	onSetFocus = "";
	onKillFocus = "";
	onKeyDown = "";
	onKeyUp = "";
	onMouseButtonDown = "";
	onMouseButtonUp = "";
	onMouseButtonClick = "";
	onMouseButtonDblClick = "";
	onMouseZChanged = "";
	onMouseMoving = "";
	onMouseHolding = "";
	onDraw = "";
};
class ctrlMapEmpty: ctrlMap
{
	ptsPerSquareSea = 1000;
	ptsPerSquareTxt = 1000;
	ptsPerSquareCLn = 1000;
	ptsPerSquareExp = 1000;
	ptsPerSquareCost = 1000;
	ptsPerSquareFor = 1000;
	ptsPerSquareForEdge = 1000;
	ptsPerSquareRoad = 1000;
	ptsPerSquareObj = 1000;
	alphaFadeStartScale = 0;
	alphaFadeEndScale = 0;
	colorBackground[] = { 1, 1, 1, 1 };
	colorOutside[] = { 1, 1, 1, 1 };
	colorSea[] = { 0, 0, 0, 0 };
	colorForest[] = { 0, 0, 0, 0 };
	colorForestBorder[] = { 0, 0, 0, 0 };
	colorRocks[] = { 0, 0, 0, 0 };
	colorRocksBorder[] = { 0, 0, 0, 0 };
	colorLevels[] = { 0, 0, 0, 0 };
	colorMainCountlines[] = { 0, 0, 0, 0 };
	colorCountlines[] = { 0, 0, 0, 0 };
	colorMainCountlinesWater[] = { 0, 0, 0, 0 };
	colorCountlinesWater[] = { 0, 0, 0, 0 };
	colorPowerLines[] = { 0, 0, 0, 0 };
	colorRailWay[] = { 0, 0, 0, 0 };
	colorNames[] = { 0, 0, 0, 0 };
	colorInactive[] = { 0, 0, 0, 0 };
	colorGrid[] = { 0, 0, 0, 0 };
	colorGridMap[] = { 0, 0, 0, 0 };
	class Task: Task
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		iconCreated = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		iconCanceled = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		iconDone = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		iconFailed = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		colorCreated[] = { 0, 0, 0, 0 };
		colorCanceled[] = { 0, 0, 0, 0 };
		colorDone[] = { 0, 0, 0, 0 };
		colorFailed[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class Waypoint: Waypoint
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class WaypointCompleted: WaypointCompleted
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class CustomMark: CustomMark
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class Command: Command
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class Bush: Bush
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class Rock: Rock
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class SmallTree: SmallTree
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class Tree: Tree
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class busstop: BusStop
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class fuelstation: FuelStation
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class hospital: Hospital
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class church: Church
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class lighthouse: Lighthouse
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class power: Power
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class powersolar: PowerSolar
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class powerwave: PowerWave
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class powerwind: PowerWind
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class quay: Quay
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class shipwreck: Shipwreck
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class transmitter: Transmitter
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class watertower: Watertower
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class Bunker: Bunker
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class Cross: Cross
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class Fortress: Fortress
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class Fountain: Fountain
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class Chapel: Chapel
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class Ruin: Ruin
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class Stack: Stack
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class Tourism: Tourism
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
	class ViewTower: ViewTower
	{
		icon = "#(argb, 8, 8, 3) color (0, 0, 0, 0) ";
		color[] = { 0, 0, 0, 0 };
		size = 0;
	};
};
class ctrlMapMain: ctrlMap
{
};
class ctrlListNBox: ctrlDefaultText
{
	type = CT_LISTNBOX;
	style = ST_MULTI;
	colorSelectBackground[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		1
	};
	colorSelectBackground2[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		1
	};
	colorText[] = { 1, 1, 1, 1 };
	colorDisabled[] = { 1, 1, 1, 0.25 };
	colorSelect[] = { 1, 1, 1, 1 };
	colorSelect2[] = { 1, 1, 1, 1 };
	colorShadow[] = { 0, 0, 0, 0.5 };
	colorPicture[] = { 1, 1, 1, 1 };
	colorPictureSelected[] = { 1, 1, 1, 1 };
	colorPictureDisabled[] = { 1, 1, 1, 0.25 };
	columns[] = { 0 };
	drawSideArrows = 0;
	idcLeft = -1;
	idcRight = -1;
	period = 1;
	disableOverflow = 0;
	rowHeight = "4.32 * (1 / (getResolution select 3)) * pixelGrid * 0.5";
	maxHistoryDelay = 1;
	soundSelect[] =
	{
		"\A3\ui_f\data\sound\RscListbox\soundSelect",
		0.09,
		1
	};
	class ListScrollBar: ScrollBar
	{
	};
	onCanDestroy = "";
	onDestroy = "";
	onSetFocus = "";
	onKillFocus = "";
	onKeyDown = "";
	onKeyUp = "";
	onMouseButtonDown = "";
	onMouseButtonUp = "";
	onMouseButtonClick = "";
	onMouseButtonDblClick = "";
	onMouseZChanged = "";
	onMouseMoving = "";
	onMouseHolding = "";
	onLBSelChanged = "";
	onLBDblClick = "";
};
class ctrlCheckboxToolbar: ctrlCheckbox
{
	color[] = { 1, 1, 1, 1 };
	colorBackgroundHover[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		1
	};
	colorBackgroundPressed[] =
	{
		" (profilenamespace getvariable ['GUI_BCG_RGB_R', 0.77]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_G', 0.51]) ",
		" (profilenamespace getvariable ['GUI_BCG_RGB_B', 0.08]) ",
		1
	};
};
